### ISSUE TITLE
index.html should be at top level, parallel to `resources` directory

### ISSUE THREAD

**Issue by derrell** [qooxdoo/qooxdoo-compiler#64] opened 2018-01-01 17:55 UTC
The relative path to the resources directory from the path where `index.html` was found should not be `../resources` as currently implemented; it should be `./resources`. The `index.html` files should therefore be placed at the top-level, not inside of the "application-name" directory where `part-*.js` are located.

**Comment by derrell** [comment] 2018-01-01 17:58
Hmmm... Then you can't have more than one target existing at one time... but still, the resources path should be relative to index.html. Maybe there should be a `build-output/resources` symbolic link to `../resources' ?

**Comment by cajus** [comment] 2018-01-01 18:29
I guess that is a duplicate of https://github.com/qooxdoo/qooxdoo-compiler/issues/57

**Comment by derrell** [comment] 2018-01-01 18:39
Yes, very similar to #57. My second comment may be more efficient -- create a symlink to the higher-level resources directory -- so that resources needn't exist in all target directories. Then again, I'm linux-centric, and symlinks are not commonly used on windows. I guess putting everything below the app directory may be more appropriate.

**Comment by cajus** [comment] 2018-01-01 18:45
From my point of view, it should output the same structure than before. @johnspackman said that he want's to make it configurable.

To be honest - being forced to use symlinks in the file system or aliases/rewrites in the web server configuration feels a bit odd. I'd expect the entry point - as you - to be at the top level. Except you've a multi application setup with shared resources - but that should not be the default.

Let's see what happens ;-)

**Comment by johnspackman** [comment] 2018-01-04 08:33
I've posted a comment on (57)[https://github.com/qooxdoo/qooxdoo-compiler/issues/57#issuecomment-355224979] but to address a couple of points raised here - the paths should all be relative to the application's `index.html`, if it's not then it's definitely a bug.

Also re: symlinks: this is possible on Windows but only when running as administrator, and there is no convenient `sudo` equivalent AFAIK.  I'm not sure it's necessary though, provided that it's OK to expose the entire target output directory

**Comment by hkollmann** [comment] 2018-02-08 22:00
Fixed with #127

**Closed by hkollmann** 2018-02-08 22:00 UTC
