### ISSUE TITLE
this.tr('') results in "Project-Id-Version: 1.0↵Report-Msgid-Bugs-To: you@…n; charset=utf-8↵Content-Trans..."

### ISSUE THREAD

**Issue by oetiker** [qooxdoo/qooxdoo-compiler#442] opened 2019-06-11 08:47 UTC
@maettu commented on [Tue Jun 11 2019](https://github.com/qooxdoo/qooxdoo/issues/9693)

**Describe the bug**
`this.tr('')` results in "Project-Id-Version: 1.0↵Report-Msgid-Bugs-To: you@…n; charset=utf-8↵Content-Transfer-Encoding: 8bit"

**To Reproduce**
1. Go to http://www.qooxdoo.org/qxl.playground/#%7B%22code%22%3A%22%252F%252F%2520Create%2520a%2520button%250Avar%2520button1%2520%253D%2520new%2520qx.ui.form.Button(this.tr('')%252C%2520%2522icon%252F22%252Fapps%252Finternet-web-browser.png%2522)%253B%250Aconsole.log(this.tr(''))%253B%250A%250A%252F%252F%2520Document%2520is%2520the%2520application%2520root%250Avar%2520doc%2520%253D%2520this.getRoot()%253B%250A%250A%252F%252F%2520Add%2520button%2520to%2520document%2520at%2520fixed%2520coordinates%250Adoc.add(button1%252C%250A%257B%250A%2520%2520left%2520%253A%2520100%252C%250A%2520%2520top%2520%2520%253A%252050%250A%257D)%253B%250A%250A%252F%252F%2520Add%2520an%2520event%2520listener%250Abutton1.addListener(%2522execute%2522%252C%2520function(e)%2520%257B%250A%2520%2520alert(this.tr(%2522Hello%2520World!%2522))%253B%250A%257D)%253B%22%2C%20%22mode%22%3A%22ria%22%7D
2. Look at javascript console or the formerly "hello world" button on the right side.

**Expected behavior**
`this.tr('')` should imo result in `''`

**Screenshots**
![Screenshot_2019-06-11_09-58-33](https://user-images.githubusercontent.com/167811/59253919-85580300-8c2f-11e9-80b4-9ccb7ce488f7.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chrome
 - Version 73.0.3683.86 (Official Build) (64-bit)

---

@hkollmann commented on [Tue Jun 11 2019](https://github.com/qooxdoo/qooxdoo/issues/9693#issuecomment-500736022)

@maettu : This seems to be a bug in playground. Please could you move the report to https://github.com/qooxdoo/qxl.playground? 
Thanks!

---

@rommni commented on [Tue Jun 11 2019](https://github.com/qooxdoo/qooxdoo/issues/9693#issuecomment-500736216)

Hum... Strange can't reproduce on chrome 74.0.3729.169 (Build officiel) (64 bits)  
![test_qx_tr](https://user-images.githubusercontent.com/907396/59254923-68bcca80-8c31-11e9-809c-8fdbe3508bf4.PNG)

---

@hkollmann commented on [Tue Jun 11 2019](https://github.com/qooxdoo/qooxdoo/issues/9693#issuecomment-500736480)

We have now seperated repositories for each application and mentain them seperatly.

---

@oetiker commented on [Tue Jun 11 2019](https://github.com/qooxdoo/qooxdoo/issues/9693#issuecomment-500746936)

@hkollmann we have not found it in playground ... but in our production app 

---

@hkollmann commented on [Tue Jun 11 2019](https://github.com/qooxdoo/qooxdoo/issues/9693#issuecomment-500747541)

Could it be a Problem of the compiler?

---

@oetiker commented on [Tue Jun 11 2019](https://github.com/qooxdoo/qooxdoo/issues/9693#issuecomment-500748038)

yes, that would be my guess ... that it associates the header of the .po file with the empty string ...

---

@hkollmann commented on [Tue Jun 11 2019](https://github.com/qooxdoo/qooxdoo/issues/9693#issuecomment-500748338)

Then we should move the issue to @qooxdoo/compiler...

**Comment by zaucker** [comment] 2019-06-11 08:51
Not sure if this helps:
https://www.gnu.org/software/gettext/manual/html_node/Header-Entry.html

But I guess this might be some default info being pulled in somehow.

**Comment by cboulanger** [comment] 2019-08-20 12:43
@oetiker can I assign this to you?

**Comment by johnspackman** [comment] 2020-05-14 17:02
The reason for this is that the Qooxdoo .po file for "en" [here](https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/translation/en.po#L3-L14) defines the empty msgid as this:

```
# English
# 
msgid ""
msgstr ""
"Project-Id-Version: qooxdoo framework\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2008-05-19 10:11+0200\n"
"PO-Revision-Date: 2007-01-23 17:53+0100\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=ASCII\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

```

But if I look at the .po file format at http://pology.nedohodnik.net/doc/user/en_US/ch-poformat.html, it says:

>2.1.2. String Wrapping
When a message is long or contains some logical line-breaks, its original and translation strings may be wrapped in the PO file (with wrapping boundary usually at column 80), such as this:

```
#: indimenu.cpp:96
msgid ""
"No INDI devices currently running. To run devices, please select devices "
"from the Device Manager in the devices menu."
msgstr ""
```

That's an untranslated example, this is translated:

```
#: indimenu.cpp:96
msgid ""
"No INDI devices (...)"
"(...) in the devices menu."
msgstr ""
"Nema INDI uređaja (...)"
"(...) u meniju uređaja."
```

So it looks to me that the Qooxdoo translation for msgid `""` should be wrapped with that whole header information block.

According to that GNU link that @zaucker posted (https://www.gnu.org/software/gettext/manual/html_node/Header-Entry.html) those are header entries, and on this page https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html#PO-Files it says:

> An empty untranslated-string is reserved to contain the header entry with the meta information (see Header Entry). This header entry should be the first entry of the file. The empty untranslated-string is reserved for this purpose and must not be used anywhere else.

So msgid `""` is reserved to have that header information - and therefore `this.tr("")` *should* return that header block.

I don't know whether the generation behaved differently, but why would you want to use `this.tr("")` anyway??

**Comment by zaucker** [comment] 2020-05-15 06:36
It seems `this.tr()` behaves "as designed". I was not aware of the special meaning of `""` as hash key of the header.
Our use case was
`someFunction(this[tr])(textVar))` and it happened that `textVar` was the empty string (intentional).
So I guess we should do `someFunction(textVar : this[tr](textVar) : textVar)`, which also would handle the `undefined` case, but is just ugly ... so I guess we should wrap that into a custom function.
So, maybe, the only "fix" for this issue would be a sentence in the docu for `tr()` mentioning this behaviour (and perhaps also the behaviour for `undefined`).

**Closed** 2020-05-20 08:46 UTC
Labels: bug
