### ISSUE TITLE
"Unresolved use of symbol" with function argument

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qooxdoo-compiler#291] opened 2019-01-25 21:14 UTC
Given this code
```javascript
qx.Class.define("qcl.ui.dialog.ServerProgress",
{
  extend : dialog.Progress,
  members :
  {
    start : function(params={})
    {
      params.id = this.getWidgetId(); //[1]
      params.auth_token = qx.core.Init.getApplication().getAccessManager().getToken(); // [2]
    }
  }  
});
```
the compiler produces these warnings:
```
qcl.ui.dialog.ServerProgress: [1] Unresolved use of symbol params.idmenu.Menu // <-- strange !
qcl.ui.dialog.ServerProgress: [2] Unresolved use of symbol params.auth_token 
```

**Comment by johnspackman** [comment] 2019-05-29 20:10
duplicate of https://github.com/qooxdoo/qooxdoo-compiler/issues/291.
fixed in https://github.com/qooxdoo/qooxdoo-compiler/pull/427

**Closed** 2019-06-05 11:32 UTC
