### ISSUE TITLE
node-sass missing after setup

### ISSUE THREAD

**Issue by oetiker** [qooxdoo/qooxdoo-compiler#817] opened 2021-06-02 07:43 UTC
When setting up qx using node 14 all seems to go well (`npm i @qooxdoo/compiler`), but then when running the compiler I get

```
 /home/oetiker/.volta/bin/npx qx compile --target=build --feedback=false --update-po-files
internal/fs/utils.js:312
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/home/oetiker/checkouts/hin-credential-mgr-stable/hin-agw-manager/frontend/node_modules/@qooxdoo/compiler/node_modules/node-sass/vendor'
    at Object.readdirSync (fs.js:1043:3)
    at Object.getInstalledBinaries (/home/oetiker/checkouts/hin-credential-mgr-stable/hin-agw-manager/frontend/node_modules/@qooxdoo/compiler/node_modules/node-sass/lib/extensions.js:133:13)
    at foundBinariesList (/home/oetiker/checkouts/hin-credential-mgr-stable/hin-agw-manager/frontend/node_modules/@qooxdoo/compiler/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/oetiker/checkouts/hin-credential-mgr-stable/hin-agw-manager/frontend/node_modules/@qooxdoo/compiler/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/oetiker/checkouts/hin-credential-mgr-stable/hin-agw-manager/frontend/node_modules/@qooxdoo/compiler/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/oetiker/checkouts/hin-credential-mgr-stable/hin-agw-manager/frontend/node_modules/@qooxdoo/compiler/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/oetiker/checkouts/hin-credential-mgr-stable/hin-agw-manager/frontend/node_modules/@qooxdoo/compiler/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /home/oetiker/checkouts/hin-credential-mgr-stable/hin-agw-manager/frontend/node_modules/@qooxdoo/compiler/lib/compiler/index.js:44898:14
    at Object.<anonymous> (/home/oetiker/checkouts/hin-credential-mgr-stable/hin-agw-manager/frontend/node_modules/@qooxdoo/compiler/lib/compiler/index.js:44995:3)
    at Module._compile (internal/modules/cjs/loader.js:1068:30) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/home/oetiker/checkouts/hin-credential-mgr-stable/hin-agw-manager/frontend/node_modules/@qooxdoo/compiler/node_modules/node-sass/vendor'
}
```
this fix is to run

```
node node_modules/@qooxdoo/compiler/node_modules/node-sass/scripts/install.js
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/linux-x64-83_binding.node
Download complete
Binary saved to /home/oetiker/checkouts/hin-credential-mgr-stable/hin-agw-manager/frontend/node_modules/@qooxdoo/compiler/node_modules/node-sass/vendor/linux-x64-83/binding.node
```

but that is not really intuitive :)

**Comment by cboulanger** [comment] 2021-06-02 07:46
Should we run this command in a post-install npm script, just to be safe?

**Comment by cboulanger** [comment] 2021-06-02 07:48
node-sass seems to be a particularly sensitive beast, this hit me several times when switching node versions, plus some absolutely cryptic "node-gyp" stuff.

**Comment by adrelino** [comment] 2021-06-02 12:02
Duplicate of https://github.com/qooxdoo/qooxdoo/issues/10189

**Comment by hkollmann** [comment] 2021-10-05 16:37
fixed with https://github.com/qooxdoo/qooxdoo-compiler/pull/823

**Closed by hkollmann** 2021-10-05 16:37 UTC
