### ISSUE TITLE
Generated index.html is always a "skeleton" one

### ISSUE THREAD

**Issue by cajus** [qooxdoo/qooxdoo-compiler#32] opened 2017-09-29 09:07 UTC
I'd expect the `source/index.html` to be taken.

**Comment by johnspackman** [comment] 2017-09-29 09:32
the problem is that there needs to be a slightly different `index.html`; `source/index.html` is also the skeleton one, just for the generator so it could be deleted when `config.json` is deleted.

I've always assumed that index.html was 100% vanilla - is there something you keep in yours?

**Comment by cajus** [comment] 2017-09-29 09:36
We've only modified `index.html` files in our projects. Either for splash screens or sorting out bad browsers early, etc. Partly adaptions needed for the header to hint for the availbility of iOS apps. Or the definition of the home icon, favicon, etc.

The generated one sets the title to "skeleton", no matter how the application is named. And it needs to be customizable IMHO.

**Comment by cajus** [comment] 2017-09-29 09:37
Maybe some kind of template with placeholders for what you need to replace/insert?

**Comment by oetiker** [comment] 2017-09-29 17:27
I already ran into this problem ... I had also expected that source/index.html was going to be used.

**Comment by johnspackman** [comment] 2017-11-01 11:41
fixed in next release; 
* the application title can be customised via `compile.json` or a fully custom index.html can be placed in `boot/index.html` 
* if there is a `source/index.html` a warning is output that it is no longer used

**Comment by cajus** [comment] 2017-11-02 20:03
@johnspackman I've a top-level `boot/index.html`, but it doesn't seem to be used at all. Assuming that the boot directory needs to be at the same level like the compile.json is.

**Comment by johnspackman** [comment] 2017-11-02 20:17
ah - I forgot that the Manifest.json needs to specify it, eg: 
```
{
	"info": { /* snip */ },
	"provides": {
		"namespace": "demoapp",
		"encoding": "utf-8",
		"class": "source/class",
		"resource": "source/resource",
		"translation": "source/translation",
		"boot": "source/boot",
		"type": "application"
	},
```

**Comment by cajus** [comment] 2017-11-02 20:20
Yeah. That works. Thanks :+1:

**Comment by johnspackman** [comment] 2017-11-02 20:57
Cool, I need to update the docs and then I'll close this

**Closed** 2017-11-13 10:41 UTC
